export declare var withStorySource: any;
export declare var __STORY__: string;
export declare var __ADDS_MAP__: {};
import './9_Atlas_controlled_xy.stories.css';
export declare const COLOR_BY_TYPE: Readonly<{
    0: string;
    1: string;
    2: string;
    3: string;
    4: string;
    5: string;
    6: string;
    7: string;
    8: string;
    9: string;
    10: string;
    11: string;
    12: string;
    13: string;
    14: string;
}>;
